name: Bug Report
description: Create a bug report to help us identify & solve issues.
title: "Bug Report: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: A description of the bug
      description: Give us a rough description of the bug you encountered.
      placeholder: Enter the description here.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Tell us what you did when you encountered the bug.
      placeholder: Enter the description here.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Tell us what was supposed to happen when you encountered  the bug.
      placeholder: Enter the description here.
    validations:
      required: true
  - type: textarea
    id: unexpected
    attributes:
      label: Unexpected behavior:
      description: Tell us what you did when you encountered the bug.
      placeholder: Enter the description here.
    validations:
      required: true
  - type: markdown
    id: screenshots
    value: "**Screenshots**"
    attributes:
      value: |
        > Attach screenshots of the bug, it helps a lot!- type: markdown
    id: screenshots
    value: "**Computer Information**"
    attributes:
      value: |
        > Tell us your computer specifications. This is not needed if you think that it's an application error.
  - type: textarea
    id: description
    attributes:
      placeholder: Enter the description here.
    validations:
      required: false
